


CREATE procedure [dbo].[up_loadLoanAppCommon]
                @pssn int
            ,   @user_id int
            ,   @user_spec int 
            ,   @efin int
            ,   @master int 
            ,   @site_id char(7)
            ,   @pri_fname char(16)
            ,   @pri_init char(1)
            ,   @pri_lname char(32)
            ,   @sec_ssn int
            ,   @sec_fname char(16)
            ,   @sec_init char(1)
            ,   @sec_lname char(32)
            ,   @address char(35)
            ,   @city char(22)
            ,   @state char(2)
            ,   @zip char(12)
            ,   @home_phone char(10)
            ,   @work_phone char(10)
            ,   @ral_flag char(1)
            ,   @refund int
            ,   @bal_due int
            ,   @tot_income int
            ,   @tot_tax int
            ,   @tot_itw int
            ,   @tot_agi int
            ,   @tot_eic smallint
            ,   @tot_dep smallint
            ,   @site_rej char(1)
            ,   @bank_id char(1)
            ,   @ero_tran_fee int
            ,   @sb_prep_fee int
            ,   @pei_prot_fee int
            ,   @ero_prot_fee int
            ,   @req_tech_fee int
            ,   @ero_bank_fee int
            ,   @split_disb_amt int
            ,   @req_bank_fee int
            ,   @req_acnt_fee int
            ,   @tax_prep_fee int
            ,   @pei_tran_fee int
            ,   @req_loan_amt int
            ,   @verify_level smallint
            ,   @filing_stat char(1)
            ,   @prep_ind char(1)
            ,   @prep_id char(8)
            ,   @cross_collect_ind char(1)
            ,   @ero_state char(2)
            ,   @email_address char(44)
            ,   @sec_email char(44)
            ,   @guid char(32)
            ,   @irs_8453OL char(1)
            ,   @roll char(1)
            ,   @ptin char(9)
            ,   @fld_8379_ind char(1)
            ,   @advnt_email_discl char(1)
            ,   @req_rush_fee int
            ,   @elf_prep_fee int
            ,   @req_cadr_fee int
            ,   @bank_stat char(1)
            ,   @adv_cmpid int
            ,   @adv_locid int
            ,   @adv_dstid int
            ,   @bnk_prim_id int
            ,   @bnk_sec_id int
            ,   @bnk_appid int
            ,   @decline_code int
			,	@irs_acc_cd char(1)
			,	@irs_acc_dt char(8)
            ,   @submission_id varchar(20)
            ,   @req_utip_fee int
            ,   @req_mmac_fee int
            ,   @req_mmip_fee int
            ,   @doc_prep_fee int
            ,   @cust_id_sha1 char(40)
            ,   @req_phone_fee int
            ,   @fst_prim_ssn int
            ,   @fst_sec_ssn int
            ,   @ral_apr int
            ,   @ral_finance_chrg int
            ,   @admin_tran_fee int
            ,   @cpts_ef_fee int
            ,   @ero_ef_fee int
            ,   @admin_ef_fee int

as

  UPDATE [dbo].[tblLoanApp] SET [pssn] = @pssn
                      ,[user_id] = @user_id
                      ,[user_spec] = @user_spec
                      ,[efin] = @efin
                      ,[master] = @master
                      ,[site_id] = @site_id
                      ,[pri_fname] = @pri_fname
                      ,[pri_init] = @pri_init
                      ,[pri_lname] = @pri_lname
                      ,[sec_ssn] = @sec_ssn
                      ,[sec_fname] = @sec_fname
                      ,[sec_init] = @sec_init
                      ,[sec_lname] = @sec_lname
                      ,[address] = @address
                      ,[city] = @city
                      ,[state] = @state
                      ,[zip] = @zip
                      ,[home_phone] = @home_phone
                      ,[work_phone] = @work_phone
                      ,[ral_flag] = @ral_flag
                      ,[refund] = @refund
                      ,[bal_due] = @bal_due
                      ,[tot_income] = @tot_income
                      ,[tot_tax] = @tot_tax
                      ,[tot_itw] = @tot_itw
                      ,[tot_agi] = @tot_agi
                      ,[tot_eic] = @tot_eic
                      ,[tot_dep] = @tot_dep
                      ,[site_rej] = @site_rej
                      ,[bank_id] = @bank_id
                      ,[pei_tran_fee] = @pei_tran_fee
                      ,[ero_tran_fee] = @ero_tran_fee
                      ,[sb_prep_fee] = @sb_prep_fee
                      ,[tax_prep_fee] = @tax_prep_fee
                      ,[ero_bank_fee] = @ero_bank_fee
                      ,[req_bank_fee] = @req_bank_fee
                      ,[req_acnt_fee] = @req_acnt_fee
                      ,[pei_prot_fee] = @pei_prot_fee
                      ,[ero_prot_fee] = @ero_prot_fee
                      ,[req_tech_fee] = @req_tech_fee
                      ,[req_loan_amt] = @req_loan_amt
                      ,[verify_level] = @verify_level
                      ,[filing_stat] = @filing_stat
                      ,[prep_ind] = @prep_ind
                      ,[prep_id] = @prep_id
                      ,[cross_collect_ind] = @cross_collect_ind
                      ,[ero_state] = @ero_state
                      ,[email_address] = @email_address
                      ,[guid] = @guid
                      ,[irs_8453OL] = @irs_8453ol
                      ,[roll] = @roll
                      ,[ptin] = @ptin
                      ,[sec_email] = @sec_email
                      ,[fld_8379_ind] = @fld_8379_ind
                      ,[advnt_email_discl] = @advnt_email_discl
                      ,[req_rush_fee] = @req_rush_fee
                      ,[req_phone_fee] = @req_phone_fee
                      ,[split_disb_amt] = @split_disb_amt
                      ,[irs_acc_dt] = @irs_acc_dt
                      ,[irs_acc_cd] = @irs_acc_cd
                      ,[elf_prep_fee] = @elf_prep_fee
                      ,[req_cadr_fee] = @req_cadr_fee
                      ,[bank_stat] = @bank_stat
                      ,[adv_cmpid] = @adv_cmpid
                      ,[adv_locid] = @adv_locid
                      ,[adv_dstid] = @adv_dstid
                      ,[bnk_prim_id] = @bnk_prim_id
                      ,[bnk_sec_id] = @bnk_sec_id
                      ,[bnk_appid] = @bnk_appid
                      ,[decline_code] = @decline_code
                      ,[submission_id] = @submission_id
                      ,[req_utip_fee] = @req_utip_fee
                      ,[req_mmac_fee] = @req_mmac_fee
                      ,[req_mmip_fee] = @req_mmip_fee
                      ,[doc_prep_fee] = @doc_prep_fee
                      ,[cust_id_sha1] = @cust_id_sha1
                      ,[fst_prim_ssn] = @fst_prim_ssn
                      ,[fst_sec_ssn] = @fst_sec_ssn
                      ,[ral_apr] = @ral_apr
                      ,[ral_finance_chrg] = @ral_finance_chrg
                      ,[admin_tran_fee] = @admin_tran_fee
                      ,[cpts_ef_fee] = @cpts_ef_fee
                      ,[ero_ef_fee] = @ero_ef_fee
                      ,[admin_ef_fee] = @admin_ef_fee
  WHERE pssn = @pssn



