CREATE TABLE [dbo].[etdfile] (
    [pssn]          VARCHAR (9)   NOT NULL,
    [stateId]       VARCHAR (2)   NOT NULL,
    [userId]        VARCHAR (6)   NULL,
    [userSpec]      INT           NULL,
    [sbId]          CHAR (6)      NULL,
    [sbSpec]        INT           NULL,
    [franId]        CHAR (6)      NULL,
    [franSpec]      INT           NULL,
    [userDcnx]      CHAR (12)     NULL,
    [rtnId]         CHAR (9)      NULL,
    [loginId]       CHAR (9)      NULL,
    [efin]          VARCHAR (6)   NULL,
    [pnamectrl]     CHAR (4)      NULL,
    [sssn]          VARCHAR (9)   NULL,
    [snamectrl]     CHAR (4)      NULL,
    [arcvno]        CHAR (8)      NULL,
    [rcpttime]      CHAR (14)     NULL,
    [timestamp]     CHAR (19)     NULL,
    [mefEligible]   CHAR (10)     NULL,
    [mefErr]        CHAR (4)      NULL,
    [form1040]      CHAR (1)      NULL,
    [submitType]    VARCHAR (15)  NULL,
    [schemaVersion] VARCHAR (50)  NULL,
    [etdFlag]       CHAR (1)      NULL,
    [irs_acc_code]  CHAR (1)      NULL,
    [irs_ack_date]  VARCHAR (8)   NULL,
    [xmit_date]     VARCHAR (8)   NULL,
    [state_no]      VARCHAR (2)   NULL,
    [rej_cnt]       VARCHAR (2)   NULL,
    [guid]          CHAR (32)     NULL,
    [submissionID]  CHAR (20)     NULL,
    [postMark]      CHAR (25)     NULL,
    [filing_stat]   CHAR (1)      NULL,
    [fetchSeq]      CHAR (4)      NULL,
    [xmit_time]     CHAR (4)      NULL,
    [recTS]         DATETIME2 (0) NULL,
    [subtype]       CHAR (2)      NULL,
    [alertcnt]      INT           NULL,
    [govcode]       CHAR (4)      NULL,
    CONSTRAINT [PK_etdfile_1] PRIMARY KEY CLUSTERED ([pssn] ASC, [stateId] ASC)
);

