CREATE TABLE [dbo].[JTHF_BankApp] (
    [JTHF_BankAppID]              INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [EfinID]                      INT          NOT NULL,
    [UserID]                      INT          CONSTRAINT [DF_JTHF_BankApp_UserID] DEFAULT ((0)) NOT NULL,
    [Master]                      INT          CONSTRAINT [DF_JTHF_BankApp_Master] DEFAULT ((0)) NOT NULL,
    [Name]                        VARCHAR (35) NULL,
    [LegalName]                   VARCHAR (50) NULL,
    [LegalEntityStatusIndicator]  VARCHAR (30) NULL,
    [OriginatingBank]             VARCHAR (15) NULL,
    [LLCMembershipRegistration]   VARCHAR (3)  NULL,
    [LocationID]                  VARCHAR (5)  NULL,
    [OfficePhoneNumber]           VARCHAR (10) NULL,
    [OfficeFaxNumber]             VARCHAR (10) NULL,
    [OfficeAddress]               VARCHAR (50) NULL,
    [OfficeCity]                  VARCHAR (35) NULL,
    [OfficeState]                 VARCHAR (2)  NULL,
    [OfficeZipCode]               VARCHAR (9)  NULL,
    [ShippingAddress]             VARCHAR (50) NULL,
    [ShippingCity]                VARCHAR (35) NULL,
    [ShippingState]               VARCHAR (2)  NULL,
    [ShippingZipCode]             VARCHAR (9)  NULL,
    [PrimaryOfficeEMail]          VARCHAR (75) NULL,
    [SecondaryOfficeEMail]        VARCHAR (75) NULL,
    [EFINOwnersFirstName]         VARCHAR (35) NULL,
    [EFINOwnersLastName]          VARCHAR (35) NULL,
    [YearsInBusiness]             INT          NULL,
    [TransmitterExperience]       VARCHAR (1)  NULL,
    [PriorYearBank]               VARCHAR (15) NULL,
    [PriorYearEFIN]               INT          NULL,
    [PriorYearBankProductsFunded] INT          NULL,
    [PriorYearLoss]               MONEY        NULL,
    [EstimatedBankProducts]       INT          NULL,
    [EstimatedCheckStock]         INT          NULL,
    [EstimatedDebitCards]         INT          NULL,
    [EstimatedCreditCards]        INT          NULL,
    [PrimaryFirstName]            VARCHAR (35) NULL,
    [PrimaryLastName]             VARCHAR (35) NULL,
    [SecondaryFirstName]          VARCHAR (35) NULL,
    [SecondaryLastName]           VARCHAR (35) NULL,
    [OwnersFirstName]             VARCHAR (35) NULL,
    [OwnersLastName]              VARCHAR (35) NULL,
    [OwnersDateOfBirth]           DATETIME     NULL,
    [OwnersAddress]               VARCHAR (50) NULL,
    [OwnersCity]                  VARCHAR (35) NULL,
    [OwnersState]                 VARCHAR (2)  NULL,
    [OwnersZipCode]               VARCHAR (9)  NULL,
    [OwnersPhoneNumber]           VARCHAR (10) NULL,
    [OwnersEIN]                   VARCHAR (9)  NULL,
    [OwnersSSN]                   VARCHAR (9)  NULL,
    [BankProducts]                VARCHAR (4)  NULL,
    [CheckPrinting]               VARCHAR (4)  NULL,
    [BankCards]                   VARCHAR (3)  NULL,
    [ComplyWithManuals]           VARCHAR (3)  NULL,
    [FeeRoutingNumber]            VARCHAR (9)  NULL,
    [FeeAccountNumber]            VARCHAR (17) NULL,
    [FeeAccountType]              VARCHAR (1)  NULL,
    [Roll]                        CHAR (1)     NULL,
    [PEITechFee]                  INT          NULL,
    [PEIRALTransmitterFee]        INT          NULL,
    [SBPrepFee]                   INT          NULL,
    [EROTranFee]                  INT          NULL,
    [DocPrepFee]                  INT          NULL,
    [Delivered]                   BIT          CONSTRAINT [DF_JTHF_BankApp_delivered] DEFAULT ((0)) NOT NULL,
    [Sent]                        BIT          CONSTRAINT [DF_JTHF_BankApp_sent] DEFAULT ((0)) NOT NULL,
    [DeliveredDate]               DATETIME     NULL,
    [SentDate]                    DATETIME     NULL,
    [AgreeBank]                   BIT          CONSTRAINT [DF_JTHF_BankApp_AgreeBank] DEFAULT ((0)) NOT NULL,
    [AgreeDate]                   DATETIME     NULL,
    [UpdatedBy]                   VARCHAR (11) NULL,
    [UpdatedDate]                 DATETIME     CONSTRAINT [DF_JTHF_BankApp_UpdatedDate] DEFAULT (getdate()) NULL,
    [Deleted]                     BIT          CONSTRAINT [DF_JTHF_BankApp_Deleted] DEFAULT ((0)) NOT NULL,
    [SubmittedRecordType]         CHAR (1)     NULL,
    [FeeAgree]                    BIT          DEFAULT ((0)) NOT NULL,
    [FeeAgreeDate]                DATETIME     NULL,
    [PEIAgree]                    BIT          DEFAULT ((0)) NOT NULL,
    [PEIAgreeDate]                DATETIME     NULL,
    [SystemHold]                  BIT          NULL,
    CONSTRAINT [PK_JTHF_BankApp] PRIMARY KEY CLUSTERED ([JTHF_BankAppID] ASC),
    CONSTRAINT [FK_JTHF_BankApp_efin] FOREIGN KEY ([EfinID]) REFERENCES [dbo].[efin] ([EfinID])
);

