CREATE TABLE [dbo].[RPTFeeSummary] (
    [pssn]          INT         NOT NULL,
    [Account]       VARCHAR (8) NOT NULL,
    [User_ID]       INT         NOT NULL,
    [EFIN]          INT         NOT NULL,
    [TaxPrepFee]    MONEY       NOT NULL,
    [ReqTechFee]    MONEY       NOT NULL,
    [PEIProtFee]    MONEY       NOT NULL,
    [EROProtFee]    MONEY       NOT NULL,
    [PEITranFee]    MONEY       NOT NULL,
    [EROTranFee]    MONEY       NOT NULL,
    [FeePayAmount]  MONEY       NOT NULL,
    [TranPayAmount] MONEY       NOT NULL,
    [PayDate]       DATE        NULL,
    [SBPayAmount]   MONEY       CONSTRAINT [DF_RPTFeeSummary_SBPayAmount] DEFAULT ((0)) NOT NULL,
    [SBPrepFee]     MONEY       CONSTRAINT [DF_RPTFeeSummary_SBPrepFee] DEFAULT ((0)) NOT NULL,
    [PPPayAmount]   MONEY       NOT NULL,
    [PPPayDate]     DATE        NULL,
    [CADRPayAmount] MONEY       NOT NULL,
    [CADRPayDate]   DATE        NULL,
    [ReqCADRFee]    MONEY       CONSTRAINT [DF__RPTFeeSum__ReqCA__56B3DD81] DEFAULT ((0)) NOT NULL,
    [CPTSAdminFee]  MONEY       NULL,
    [ChkAdminFee]   MONEY       NULL,
    [DocPrepFee]    MONEY       NULL,
    [ELFPrepFee]    MONEY       NULL,
    [CPTS_Ef_Fee]   MONEY       NULL,
    CONSTRAINT [PK_RPTTransmitterAddOn] PRIMARY KEY CLUSTERED ([pssn] ASC)
);

