CREATE TABLE [dbo].[tblItinMaster] (
    [UserID]                 INT           NOT NULL,
    [GUID]                   VARCHAR (255) NOT NULL,
    [PrimarySSN]             INT           NULL,
    [FilingStatus]           TINYINT       NULL,
    [SenderID]               INT           NULL,
    [PrimaryFirstName]       VARCHAR (255) NULL,
    [PrimaryLastName]        VARCHAR (255) NULL,
    [PrimaryMiddleInitial]   VARCHAR (255) NULL,
    [SecondarySSN]           VARCHAR (255) NULL,
    [SecondaryFirstName]     VARCHAR (255) NULL,
    [SecondaryLastName]      VARCHAR (255) NULL,
    [SecondaryMiddleInitial] VARCHAR (255) NULL,
    [SiteID]                 VARCHAR (255) NULL,
    [PaidPreparerID]         VARCHAR (255) NULL,
    [EFIN]                   VARCHAR (255) NULL,
    [RALF]                   VARCHAR (255) NULL,
    [TransmitDate]           VARCHAR (255) NULL,
    [TransmitTime]           VARCHAR (255) NULL,
    [PrintFinal]             CHAR (8)      NULL,
    [PrepFee]                INT           NULL,
    [SBFee]                  INT           NULL,
    [PEIProtPlusFee]         INT           NULL,
    [BankProductAttached]    BIT           NULL,
    [HealthQuestion1]        CHAR (1)      NULL,
    [HealthQuestion2]        CHAR (1)      NULL,
    [HealthQuestion3]        CHAR (1)      NULL,
    [HealthCareID]           VARCHAR (255) NULL,
    [PrimaryPhone]           CHAR (10)     NULL,
    [PrimaryWork]            CHAR (10)     NULL,
    [PrimaryCell]            CHAR (10)     NULL,
    [PrimaryEmail]           VARCHAR (255) NULL,
    [RefferalType]           VARCHAR (255) NULL,
    [RefferalText]           VARCHAR (255) NULL,
    [Address]                VARCHAR (255) NULL,
    [City]                   VARCHAR (255) NULL,
    [State]                  CHAR (2)      NULL,
    [Zip]                    CHAR (12)     NULL,
    [PreparerName]           VARCHAR (255) NULL,
    [PTIN]                   CHAR (9)      NULL,
    [DependentCount]         INT           NULL,
    [Discount]               INT           NULL,
    [ScheduleA]              TINYINT       NULL,
    [ScheduleC]              TINYINT       NULL,
    [form_type_1040]         CHAR (1)      NULL,
    [recTS]                  DATETIME2 (0) NULL,
    [FLD1272]                INT           NULL,
    [FLD1274]                CHAR (1)      NULL,
    [FLD1276]                CHAR (1)      NULL,
    [FLD1278]                CHAR (17)     NULL,
    [NonFinInvTotal]         INT           NULL,
    [TaxpayeriProtectID]     VARCHAR (9)   NULL,
    [TaxpayerDOB]            DATE          NULL,
    [SpouseiProtectID]       VARCHAR (9)   NULL,
    [SpouseDOB]              DATE          NULL,
    [TaxpayerAgreeDate]      DATE          NULL,
    [SpouseAgreeDate]        DATE          NULL,
    [req_utip_fee]           INT           NULL,
    [req_mmac_fee]           INT           NULL,
    [req_mmip_fee]           INT           NULL,
    [ret_stat]               CHAR (1)      NULL,
    [AncillaryCode]          CHAR (4)      NULL,
    [CreatedReturnDate]      DATETIME      NULL,
    [SecondaryHome]          CHAR (10)     NULL,
    [SecondaryWork]          CHAR (10)     NULL,
    [SecondaryCell]          CHAR (10)     NULL,
    [ModifiedDate]           DATETIME2 (7) CONSTRAINT [DF_tblItinMaster_ModifiedDate] DEFAULT (getdate()) NULL,
    [CreatedDate]            DATETIME2 (7) DEFAULT (getdate()) NOT NULL,
    [advOptOut]              BIT           DEFAULT ((0)) NOT NULL,
    [advRequestDate]         DATETIME      NULL,
    [ScheduleCEz]            TINYINT       NULL,
    [Form8863]               TINYINT       NULL,
    [DisabledDependent]      TINYINT       NULL,
    [ExternalId]             CHAR (26)     NULL,
    [InvTotalPayments]       INT           NULL,
    [referral]               BIT           DEFAULT ((0)) NOT NULL,
    [referralName]           VARCHAR (80)  NULL,
    [referralSSN]            CHAR (9)      NULL,
    [referralPhone]          CHAR (10)     NULL,
    [referralAddress]        VARCHAR (35)  NULL,
    [referralCity]           VARCHAR (35)  NULL,
    [referralState]          CHAR (2)      NULL,
    [referralZipCode]        VARCHAR (12)  NULL,
    [HCQ9]                   BIT           DEFAULT ((0)) NOT NULL,
    [referralDate]           DATE          NULL,
    [RowVer]                 ROWVERSION    NOT NULL,
    [nRowVer]                AS            (CONVERT([bigint],[RowVer],(0))) PERSISTED,
    [bankAcctType]           CHAR (1)      NULL,
    [referralIDScanned]      BIT           NULL,
    [CDSj_q1]                BIT           CONSTRAINT [df_tblItinMaster_CDSj_q1] DEFAULT ((0)) NULL,
    [CDSj_q2]                BIT           CONSTRAINT [df_tblItinMaster_CDSj_q2] DEFAULT ((0)) NULL,
    [CDSj_q3]                BIT           CONSTRAINT [df_tblItinMaster_CDSj_q3] DEFAULT ((0)) NULL,
    [CDSj_q4]                BIT           CONSTRAINT [df_tblItinMaster_CDSj_q4] DEFAULT ((0)) NULL,
    [qualifyException]       BIT           CONSTRAINT [df_tblItinMaster_qualifyException] DEFAULT ((0)) NULL,
    [CustomerAdvance]        INT           NULL,
    [userStatus]             VARCHAR (7)   NULL,
    [EIP]                    CHAR (1)      NULL,
    [charge_subtotal1]       INT           NULL,
    [discount_subtotal]      INT           NULL,
    [charge_subtotal2]       INT           NULL,
    [payment_subtotal]       INT           NULL,
    [prior_year_balance]     INT           NULL,
    [net_invoice]            INT           NULL,
    [PaperFileRT]            CHAR (1)      NULL,
    [ImportAPIK]             VARCHAR (32)  NULL,
    [ImportAPIKey]           VARCHAR (64)  NULL,
    CONSTRAINT [PK_tblItinMaster] PRIMARY KEY CLUSTERED ([UserID] ASC, [GUID] ASC)
);

