CREATE TABLE [dbo].[tblLoanApp] (
    [pssn]                 INT           NOT NULL,
    [bankapp_id]           INT           NULL,
    [status]               CHAR (1)      NULL,
    [RejectCode]           VARCHAR (50)  NULL,
    [RejectDescription]    VARCHAR (255) NULL,
    [user_id]              INT           NOT NULL,
    [user_spec]            INT           NULL,
    [efin]                 INT           NULL,
    [master]               INT           NULL,
    [site_id]              CHAR (7)      NULL,
    [pri_fname]            CHAR (16)     NULL,
    [pri_init]             CHAR (1)      NULL,
    [pri_lname]            CHAR (32)     NULL,
    [pri_dob]              CHAR (8)      NULL,
    [sec_ssn]              INT           NOT NULL,
    [sec_fname]            CHAR (16)     NULL,
    [sec_init]             CHAR (1)      NULL,
    [sec_lname]            CHAR (32)     NULL,
    [sec_dob]              CHAR (8)      NULL,
    [address]              CHAR (35)     NULL,
    [city]                 CHAR (22)     NULL,
    [state]                CHAR (2)      NULL,
    [zip]                  CHAR (12)     NULL,
    [res_address]          CHAR (35)     NULL,
    [res_city]             CHAR (22)     NULL,
    [res_state]            CHAR (2)      NULL,
    [res_zip]              CHAR (12)     NULL,
    [home_phone]           CHAR (10)     NULL,
    [work_phone]           CHAR (10)     NULL,
    [ral_flag]             CHAR (1)      NULL,
    [refund]               INT           NOT NULL,
    [bal_due]              INT           NOT NULL,
    [fld_1272]             CHAR (9)      NULL,
    [fld_1278]             CHAR (17)     NULL,
    [fld_1274]             CHAR (1)      NULL,
    [fld_1276]             CHAR (1)      NULL,
    [tot_income]           INT           NOT NULL,
    [tot_tax]              INT           NOT NULL,
    [tot_itw]              INT           NOT NULL,
    [tot_agi]              INT           NOT NULL,
    [tot_eic]              SMALLINT      NULL,
    [tot_dep]              SMALLINT      NULL,
    [fld_eicf]             CHAR (1)      NULL,
    [site_rej]             CHAR (1)      NULL,
    [verify_errors]        SMALLINT      NULL,
    [import_errors]        SMALLINT      NULL,
    [bank_id]              CHAR (1)      NULL,
    [pei_tran_fee]         INT           NOT NULL,
    [ero_tran_fee]         INT           NOT NULL,
    [sb_prep_fee]          INT           NOT NULL,
    [tax_prep_fee]         INT           NOT NULL,
    [ero_bank_fee]         INT           NOT NULL,
    [req_bank_fee]         INT           NOT NULL,
    [req_acnt_fee]         INT           NOT NULL,
    [pei_prot_fee]         INT           NOT NULL,
    [ero_prot_fee]         INT           NOT NULL,
    [req_tech_fee]         INT           NOT NULL,
    [req_loan_amt]         INT           NOT NULL,
    [verify_level]         SMALLINT      NULL,
    [filing_stat]          CHAR (1)      NULL,
    [prep_ind]             CHAR (1)      NULL,
    [prep_id]              CHAR (8)      NULL,
    [cross_collect_ind]    CHAR (1)      NULL,
    [w2_ein]               INT           NULL,
    [w2_cnt]               SMALLINT      NULL,
    [ero_state]            CHAR (2)      NULL,
    [sig_date]             CHAR (8)      NULL,
    [all_state_rfnd]       INT           NULL,
    [state_rac]            CHAR (1)      NULL,
    [pt_rtn]               CHAR (9)      NULL,
    [pt_dan]               CHAR (17)     NULL,
    [pt_acnt_type]         CHAR (1)      NULL,
    [cash_card]            CHAR (17)     NULL,
    [email_address]        CHAR (44)     NULL,
    [guid]                 CHAR (32)     NULL,
    [rsrvd_ip_addr]        CHAR (1)      NULL,
    [irs_8453OL]           CHAR (1)      NULL,
    [verify_addr_ind]      CHAR (1)      NULL,
    [alt_addr_ind]         CHAR (1)      NULL,
    [alt_addr_descr]       CHAR (30)     NULL,
    [prim_1st_id_type]     CHAR (1)      NULL,
    [prim_1st_id_descr]    CHAR (20)     NULL,
    [prim_1st_id_nbr]      CHAR (20)     NULL,
    [prim_1st_id_place]    CHAR (22)     NULL,
    [prim_1st_id_issued]   CHAR (8)      NULL,
    [prim_1st_id_expire]   CHAR (8)      NULL,
    [prim_1st_id_info]     CHAR (35)     NULL,
    [prim_1st_id_dflag]    CHAR (1)      NULL,
    [prim_1st_id_dreas]    CHAR (20)     NULL,
    [prim_2nd_id_type]     CHAR (1)      NULL,
    [prim_2nd_id_descr]    CHAR (52)     NULL,
    [prim_2nd_id_nbr]      CHAR (20)     NULL,
    [prim_2nd_id_place]    CHAR (22)     NULL,
    [prim_2nd_id_issued]   CHAR (8)      NULL,
    [prim_2nd_id_expire]   CHAR (8)      NULL,
    [prim_2nd_id_dflag]    CHAR (1)      NULL,
    [prim_2nd_id_dreas]    CHAR (20)     NULL,
    [prim_3rd_id_type]     CHAR (1)      NULL,
    [prim_3rd_id_descr]    CHAR (52)     NULL,
    [prim_3rd_id_nbr]      CHAR (20)     NULL,
    [prim_3rd_id_place]    CHAR (22)     NULL,
    [prim_3rd_id_issued]   CHAR (8)      NULL,
    [prim_3rd_id_expire]   CHAR (8)      NULL,
    [prim_3rd_id_dflag]    CHAR (1)      NULL,
    [prim_3rd_id_dreas]    CHAR (20)     NULL,
    [sec_1st_id_type]      CHAR (1)      NULL,
    [sec_1st_id_descr]     CHAR (20)     NULL,
    [sec_1st_id_nbr]       CHAR (20)     NULL,
    [sec_1st_id_place]     CHAR (22)     NULL,
    [sec_1st_id_issued]    CHAR (8)      NULL,
    [sec_1st_id_expire]    CHAR (8)      NULL,
    [sec_1st_id_info]      CHAR (35)     NULL,
    [sec_1st_id_dflag]     CHAR (1)      NULL,
    [sec_1st_id_dreas]     CHAR (20)     NULL,
    [sec_2nd_id_type]      CHAR (1)      NULL,
    [sec_2nd_id_descr]     CHAR (52)     NULL,
    [sec_2nd_id_nbr]       CHAR (20)     NULL,
    [sec_2nd_id_place]     CHAR (22)     NULL,
    [sec_2nd_id_issued]    CHAR (8)      NULL,
    [sec_2nd_id_expire]    CHAR (8)      NULL,
    [sec_2nd_id_dflag]     CHAR (1)      NULL,
    [sec_2nd_id_dreas]     CHAR (20)     NULL,
    [sec_3rd_id_type]      CHAR (1)      NULL,
    [sec_3rd_id_descr]     CHAR (52)     NULL,
    [sec_3rd_id_nbr]       CHAR (20)     NULL,
    [sec_3rd_id_place]     CHAR (22)     NULL,
    [sec_3rd_id_issued]    CHAR (8)      NULL,
    [sec_3rd_id_expire]    CHAR (8)      NULL,
    [sec_3rd_id_dflag]     CHAR (1)      NULL,
    [sec_3rd_id_dreas]     CHAR (20)     NULL,
    [borr_ind]             CHAR (1)      NULL,
    [mil_ind]              CHAR (1)      NULL,
    [due_dil_ind]          CHAR (1)      NULL,
    [prot_plus]            CHAR (1)      NULL,
    [lexis_nexis]          CHAR (1)      NULL,
    [pref_contact]         CHAR (1)      NULL,
    [roll]                 CHAR (1)      NULL,
    [ptin]                 CHAR (9)      NULL,
    [esig_flag]            CHAR (1)      NULL,
    [dep_1_lname]          CHAR (15)     NULL,
    [dep_1_rel]            CHAR (11)     NULL,
    [dep_2_lname]          CHAR (15)     NULL,
    [dep_2_rel]            CHAR (11)     NULL,
    [dep_3_lname]          CHAR (15)     NULL,
    [dep_3_rel]            CHAR (11)     NULL,
    [dep_4_lname]          CHAR (15)     NULL,
    [dep_4_rel]            CHAR (11)     NULL,
    [wages]                INT           NOT NULL,
    [schc_incomeloss]      INT           NOT NULL,
    [other_gainloss]       INT           NOT NULL,
    [sche_incomeloss]      INT           NOT NULL,
    [farm_incomeloss]      INT           NOT NULL,
    [total_item_std_ded]   INT           NOT NULL,
    [child_tax_credit]     INT           NOT NULL,
    [edu_credit]           INT           NOT NULL,
    [est_tax_pay]          INT           NOT NULL,
    [occupation]           CHAR (25)     NULL,
    [eic_dep_1_lname]      CHAR (15)     NULL,
    [eic_dep_1_byear]      CHAR (4)      NULL,
    [eic_dep_1_rel]        CHAR (11)     NULL,
    [eic_dep_2_lname]      CHAR (15)     NULL,
    [eic_dep_2_byear]      CHAR (4)      NULL,
    [eic_dep_2_rel]        CHAR (11)     NULL,
    [eic_dep_3_lname]      CHAR (15)     NULL,
    [eic_dep_3_byear]      CHAR (4)      NULL,
    [eic_dep_3_rel]        CHAR (11)     NULL,
    [prim_secq]            CHAR (1)      NULL,
    [prim_seca]            CHAR (25)     NULL,
    [prim_lang]            CHAR (1)      NULL,
    [prim_contact_meth]    CHAR (1)      NULL,
    [prim_cell]            CHAR (10)     NULL,
    [prim_cell_carrier]    CHAR (2)      NULL,
    [prim_citizen]         CHAR (1)      NULL,
    [prim_citizen_country] CHAR (20)     NULL,
    [sec_secq]             CHAR (1)      NULL,
    [sec_seca]             CHAR (25)     NULL,
    [sec_lang]             CHAR (1)      NULL,
    [sec_contact_meth]     CHAR (1)      NULL,
    [sec_cell]             CHAR (10)     NULL,
    [sec_cell_carrier]     CHAR (2)      NULL,
    [sec_citizen]          CHAR (1)      NULL,
    [sec_citizen_country]  CHAR (20)     NULL,
    [sec_email]            CHAR (44)     NULL,
    [fld_8836_ind]         CHAR (1)      NULL,
    [fld_8862_ind]         CHAR (1)      NULL,
    [sig_ver_user]         CHAR (1)      NULL,
    [sig_ver_disclose]     CHAR (1)      NULL,
    [sig_ver_bankapp]      CHAR (1)      NULL,
    [sig_ver_tila]         CHAR (1)      NULL,
    [advnt_sendsms]        CHAR (1)      NULL,
    [advnt_sendemail]      CHAR (1)      NULL,
    [disb_type]            CHAR (1)      NULL,
    [ext_pay_amt]          INT           NULL,
    [fld_8379_ind]         CHAR (1)      NULL,
    [advnt_email_discl]    CHAR (1)      NULL,
    [req_rush_fee]         INT           NOT NULL,
    [req_phone_fee]        INT           NULL,
    [split_disb_amt]       INT           NULL,
    [ip_addr]              CHAR (15)     NULL,
    [insertDate]           DATETIME      CONSTRAINT [DF_tblLoanApp_insertDate] DEFAULT (getdate()) NULL,
    [irs_acc_dt]           DATETIME      NULL,
    [irs_acc_cd]           CHAR (1)      NULL,
    [sub_date]             DATETIME      NULL,
    [resp_date]            DATETIME      NULL,
    [batch]                CHAR (9)      NULL,
    [elf_prep_fee]         INT           NULL,
    [req_cadr_fee]         INT           NULL,
    [doc_signer]           VARCHAR (22)  NULL,
    [doc_tp]               CHAR (1)      NULL,
    [doc_prep]             CHAR (1)      NULL,
    [bank_stat]            CHAR (1)      NULL,
    [adv_cmpid]            INT           NULL,
    [adv_locid]            INT           NULL,
    [adv_dstid]            INT           NULL,
    [bnk_prim_id]          INT           NULL,
    [bnk_sec_id]           INT           NULL,
    [bnk_appid]            INT           NULL,
    [form_type_1040]       CHAR (1)      NULL,
    [decline_code]         INT           NULL,
    [submission_id]        VARCHAR (20)  NULL,
    [req_utip_fee]         INT           DEFAULT ((0)) NOT NULL,
    [req_mmac_fee]         INT           DEFAULT ((0)) NOT NULL,
    [req_mmip_fee]         INT           DEFAULT ((0)) NOT NULL,
    [padp_flag]            CHAR (1)      NULL,
    [doc_prep_fee]         INT           DEFAULT ((0)) NOT NULL,
    [rf_loan_ind]          CHAR (1)      NULL,
    [fst_bnk_print_dt]     DATETIME      NULL,
    [lst_bnk_print_dt]     DATETIME      NULL,
    [cust_id_sha1]         CHAR (40)     NULL,
    [rt_lite_ind]          CHAR (1)      NULL,
    [fst_req_bank_fee]     INT           DEFAULT ((0)) NOT NULL,
    [fst_req_acnt_fee]     INT           DEFAULT ((0)) NOT NULL,
    [fst_req_loan_amt]     INT           DEFAULT ((0)) NOT NULL,
    [fst_tax_prep_fee]     INT           DEFAULT ((0)) NOT NULL,
    [fst_pei_tran_fee]     INT           DEFAULT ((0)) NOT NULL,
    [fst_ero_tran_fee]     INT           DEFAULT ((0)) NOT NULL,
    [fst_sb_prep_fee]      INT           DEFAULT ((0)) NOT NULL,
    [fst_pei_prot_fee]     INT           DEFAULT ((0)) NOT NULL,
    [fst_ero_prot_fee]     INT           DEFAULT ((0)) NOT NULL,
    [fst_req_tech_fee]     INT           DEFAULT ((0)) NOT NULL,
    [fst_prod_type]        CHAR (1)      NULL,
    [lst_req_bank_fee]     INT           DEFAULT ((0)) NOT NULL,
    [lst_req_acnt_fee]     INT           DEFAULT ((0)) NOT NULL,
    [lst_req_loan_amt]     INT           DEFAULT ((0)) NOT NULL,
    [lst_tax_prep_fee]     INT           DEFAULT ((0)) NOT NULL,
    [lst_pei_tran_fee]     INT           DEFAULT ((0)) NOT NULL,
    [lst_ero_tran_fee]     INT           DEFAULT ((0)) NOT NULL,
    [lst_sb_prep_fee]      INT           DEFAULT ((0)) NOT NULL,
    [lst_pei_prot_fee]     INT           DEFAULT ((0)) NOT NULL,
    [lst_ero_prot_fee]     INT           DEFAULT ((0)) NOT NULL,
    [lst_req_tech_fee]     INT           DEFAULT ((0)) NOT NULL,
    [lst_prod_type]        CHAR (1)      NULL,
    [fst_aprod_tag1]       CHAR (3)      DEFAULT ('   ') NOT NULL,
    [fst_aprod_type1]      TINYINT       DEFAULT ((0)) NOT NULL,
    [fst_aprod_base1]      INT           DEFAULT ((0)) NOT NULL,
    [fst_aprod_addon1]     INT           DEFAULT ((0)) NOT NULL,
    [fst_aprod_tag2]       CHAR (3)      DEFAULT ('   ') NOT NULL,
    [fst_aprod_type2]      TINYINT       DEFAULT ((0)) NOT NULL,
    [fst_aprod_base2]      INT           DEFAULT ((0)) NOT NULL,
    [fst_aprod_addon2]     INT           DEFAULT ((0)) NOT NULL,
    [fst_aprod_tag3]       CHAR (3)      DEFAULT ('   ') NOT NULL,
    [fst_aprod_type3]      TINYINT       DEFAULT ((0)) NOT NULL,
    [fst_aprod_base3]      INT           DEFAULT ((0)) NOT NULL,
    [fst_aprod_addon3]     INT           DEFAULT ((0)) NOT NULL,
    [fst_aprod_tag4]       CHAR (3)      DEFAULT ('   ') NOT NULL,
    [fst_aprod_type4]      TINYINT       DEFAULT ((0)) NOT NULL,
    [fst_aprod_base4]      INT           DEFAULT ((0)) NOT NULL,
    [fst_aprod_addon4]     INT           DEFAULT ((0)) NOT NULL,
    [fst_aprod_tag5]       CHAR (3)      DEFAULT ('   ') NOT NULL,
    [fst_aprod_type5]      TINYINT       DEFAULT ((0)) NOT NULL,
    [fst_aprod_base5]      INT           DEFAULT ((0)) NOT NULL,
    [fst_aprod_addon5]     INT           DEFAULT ((0)) NOT NULL,
    [fst_prim_ssn]         INT           NULL,
    [fst_sec_ssn]          INT           NULL,
    [ral_apr]              INT           NULL,
    [ral_finance_chrg]     INT           NULL,
    [admin_tran_fee]       INT           NULL,
    [cpts_ef_fee]          INT           NULL,
    [ero_ef_fee]           INT           NULL,
    [admin_ef_fee]         INT           NULL,
    [fst_cpts_ef_fee]      INT           NULL,
    [fst_ero_ef_fee]       INT           NULL,
    [fst_admin_ef_fee]     INT           NULL,
    CONSTRAINT [PK_tblLoanApp] PRIMARY KEY CLUSTERED ([pssn] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ID1_tblLoanApp]
    ON [dbo].[tblLoanApp]([bank_id] ASC, [status] ASC);


GO
CREATE NONCLUSTERED INDEX [ID2_tblLoanApp]
    ON [dbo].[tblLoanApp]([batch] ASC);


GO

CREATE TRIGGER trg_tblLoanApp_update
   ON  tblLoanApp
   AFTER UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

    insert ztblLoanAppLog
        select 
            i.pssn
        ,   'update'
        ,   getdate()
        from 
            inserted i

END

GO
DISABLE TRIGGER [dbo].[trg_tblLoanApp_update]
    ON [dbo].[tblLoanApp];


GO

CREATE TRIGGER trg_tblLoanApp_insert
   ON  tblLoanApp
   AFTER INSERT
AS 
BEGIN
	SET NOCOUNT ON;

    insert ztblLoanAppLog
        select 
            i.pssn
        ,   'insert'
        ,   getdate()
        from 
            inserted i

END

GO
DISABLE TRIGGER [dbo].[trg_tblLoanApp_insert]
    ON [dbo].[tblLoanApp];

