CREATE TABLE [dbo].[tblXlinkEFINDatabase] (
    [efin_id]              INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [create_date]          DATETIME     CONSTRAINT [DF_tblEFINDatabase_create_date] DEFAULT (getdate()) NULL,
    [edit_date]            DATETIME     CONSTRAINT [DF_tblEFINDatabase_edit_date] DEFAULT (getdate()) NULL,
    [publish_date]         DATETIME     NULL,
    [account_id]           VARCHAR (8)  NULL,
    [user_id]              INT          NULL,
    [bank]                 CHAR (1)     NULL,
    [efin]                 CHAR (6)     NULL,
    [company_name]         VARCHAR (35) NULL,
    [self_employed]        CHAR (1)     NULL,
    [ssn]                  CHAR (9)     NULL,
    [ein]                  CHAR (9)     NULL,
    [address]              VARCHAR (35) NULL,
    [city]                 VARCHAR (22) NULL,
    [state]                CHAR (2)     NULL,
    [zip]                  VARCHAR (12) NULL,
    [office_phone]         CHAR (10)    NULL,
    [first_dcn]            VARCHAR (5)  NULL,
    [state_code_1]         CHAR (2)     NULL,
    [state_id_1]           VARCHAR (14) NULL,
    [state_code_2]         CHAR (2)     NULL,
    [state_id_2]           VARCHAR (14) NULL,
    [sbin]                 VARCHAR (6)  NULL,
    [special_bank_app_loc] VARCHAR (3)  NULL,
    [default_pin]          VARCHAR (5)  NULL,
    [transmitter_fee]      MONEY        NULL,
    [sb_fee]               MONEY        NULL,
    [sb_name]              VARCHAR (15) NULL,
    [sb_fee_all]           CHAR (1)     NULL,
    [franchiseuser_id]     INT          NULL,
    [cell_phone]           CHAR (10)    NULL,
    [cell_phone_carrier]   VARCHAR (35) NULL,
    CONSTRAINT [PK_tblEFINDatabase] PRIMARY KEY CLUSTERED ([efin_id] ASC)
);

