CREATE TABLE [dbo].[user_regr] (
    [reg_user_id]      VARCHAR (6)   NOT NULL,
    [reg_password]     VARCHAR (8)   NULL,
    [reg_hold_flg]     VARCHAR (1)   NULL,
    [reg_bank_id]      VARCHAR (1)   NULL,
    [reg_office_id]    VARCHAR (6)   NULL,
    [reg_mail_cnt]     VARCHAR (6)   NULL,
    [reg_alt_user_id]  VARCHAR (6)   NULL,
    [reg_process_code] VARCHAR (1)   NULL,
    [reg_date]         VARCHAR (10)  NULL,
    [reg_line_num]     VARCHAR (2)   NULL,
    [reg_call_num]     VARCHAR (4)   NULL,
    [reg_call_len]     VARCHAR (6)   NULL,
    [reg_cps]          VARCHAR (4)   NULL,
    [reg_last_call]    VARCHAR (12)  NULL,
    [reg_address]      VARCHAR (40)  NULL,
    [reg_box_large]    VARCHAR (1)   NULL,
    [reg_dcnx]         VARCHAR (5)   NULL,
    [reg_dbug_flg]     VARCHAR (1)   NULL,
    [reg_serial]       VARCHAR (8)   NULL,
    [reg_level]        VARCHAR (6)   NULL,
    [reg_novell]       VARCHAR (1)   NULL,
    [reg_company]      VARCHAR (40)  NULL,
    [reg_phone]        VARCHAR (10)  NULL,
    [reg_pid]          VARCHAR (9)   NULL,
    [reg_rtn_cnt]      VARCHAR (6)   NULL,
    [reg_stmt_hdr]     VARCHAR (1)   NULL,
    [reg_transcrib]    VARCHAR (1)   NULL,
    [reg_asgn_dcn]     VARCHAR (1)   NULL,
    [reg_stock]        VARCHAR (1)   NULL,
    [reg_chk_num]      VARCHAR (8)   NULL,
    [reg_cpid]         VARCHAR (6)   NULL,
    [reg_dflt_dcn]     VARCHAR (5)   NULL,
    [reg_doc_fee]      VARCHAR (4)   NULL,
    [reg_dflt_ral]     VARCHAR (1)   NULL,
    [reg_elf_fee]      VARCHAR (4)   NULL,
    [reg_efin]         VARCHAR (6)   NULL,
    [reg_sbid]         VARCHAR (6)   NULL,
    [reg_chk_top]      VARCHAR (2)   NULL,
    [reg_dmpr_flg]     VARCHAR (1)   NULL,
    [reg_laser_fonts]  VARCHAR (1)   NULL,
    [reg_lsri_flg]     VARCHAR (1)   NULL,
    [reg_lsrq_flg]     VARCHAR (1)   NULL,
    [reg_lsrw_flg]     VARCHAR (1)   NULL,
    [reg_chk_port]     VARCHAR (1)   NULL,
    [reg_prt_path]     VARCHAR (255) NULL,
    [reg_copy_dcn]     VARCHAR (1)   NULL,
    [reg_exp_path]     VARCHAR (255) NULL,
    [reg_fixd_fmt]     VARCHAR (1)   NULL,
    [reg_imp_path]     VARCHAR (255) NULL,
    [reg_imp_patt]     VARCHAR (12)  NULL,
    [reg_upd_path]     VARCHAR (255) NULL,
    [reg_xfr_path]     VARCHAR (255) NULL,
    [reg_yty_path]     VARCHAR (255) NULL,
    [reg_baud]         VARCHAR (1)   NULL,
    [reg_com]          VARCHAR (1)   NULL,
    [reg_connect]      VARCHAR (18)  NULL,
    [reg_cts]          VARCHAR (1)   NULL,
    [reg_dial]         VARCHAR (6)   NULL,
    [reg_dial_pfx]     VARCHAR (12)  NULL,
    [reg_drop]         VARCHAR (2)   NULL,
    [reg_irq]          VARCHAR (1)   NULL,
    [reg_modm_nam]     VARCHAR (12)  NULL,
    [reg_reset]        VARCHAR (28)  NULL,
    [reg_stop]         VARCHAR (1)   NULL,
    [reg_time_out]     VARCHAR (2)   NULL,
    [reg_modem_id]     VARCHAR (5)   NULL,
    [reg_max_xfrs]     VARCHAR (1)   NULL,
    [reg_netwrk]       VARCHAR (28)  NULL,
    [reg_sft_pkg_a]    VARCHAR (2)   NULL,
    [reg_sft_rel_a]    VARCHAR (1)   NULL,
    [reg_sft_offset_a] VARCHAR (5)   NULL,
    [reg_sft_ver_a]    SMALLINT      NULL,
    [reg_sft_beta_a]   SMALLINT      NULL,
    [reg_sft_pkg_b]    VARCHAR (2)   NULL,
    [reg_sft_rel_b]    VARCHAR (1)   NULL,
    [reg_sft_offset_b] VARCHAR (5)   NULL,
    [reg_sft_ver_b]    SMALLINT      NULL,
    [reg_sft_beta_b]   SMALLINT      NULL,
    [reg_sft_pkg_c]    VARCHAR (2)   NULL,
    [reg_sft_rel_c]    VARCHAR (1)   NULL,
    [reg_sft_offset_c] VARCHAR (5)   NULL,
    [reg_sft_ver_c]    SMALLINT      NULL,
    [reg_sft_beta_c]   SMALLINT      NULL,
    [reg_sft_pkg_d]    VARCHAR (2)   NULL,
    [reg_sft_rel_d]    VARCHAR (1)   NULL,
    [reg_sft_offset_d] VARCHAR (5)   NULL,
    [reg_sft_ver_d]    SMALLINT      NULL,
    [reg_sft_beta_d]   SMALLINT      NULL,
    [reg_sft_pkg_e]    VARCHAR (2)   NULL,
    [reg_sft_rel_e]    VARCHAR (1)   NULL,
    [reg_sft_offset_e] VARCHAR (5)   NULL,
    [reg_sft_ver_e]    SMALLINT      NULL,
    [reg_sft_beta_e]   SMALLINT      NULL,
    [reg_sft_pkg_f]    VARCHAR (2)   NULL,
    [reg_sft_rel_f]    VARCHAR (1)   NULL,
    [reg_sft_offset_f] VARCHAR (5)   NULL,
    [reg_sft_ver_f]    SMALLINT      NULL,
    [reg_sft_beta_f]   SMALLINT      NULL,
    [reg_state_id]     VARCHAR (2)   NULL,
    [reg_state_ver]    VARCHAR (1)   NULL,
    [reg_toss_ack]     VARCHAR (1)   NULL,
    [reg_reset_id]     VARCHAR (8)   NULL,
    [reg_reset_site]   CHAR (7)      NULL,
    [reg_autx]         CHAR (1)      NULL,
    [reg_autc]         CHAR (1)      NULL,
    [reg_dxfr]         CHAR (1)      NULL,
    [reg_xmit]         CHAR (1)      NULL,
    CONSTRAINT [PK__user_regr__060DEAE8] PRIMARY KEY CLUSTERED ([reg_user_id] ASC)
);

